const data = [
  {
    title: '首页',
    path: '/home',
    file: '/view/home/index.vue',
    icon: 'HomeOutline',
    keepAlive: true,
    tabFix: true,
    order: 100,
    permission: 'ROLE_USER',
  },
  {
    title: '系统设置',
    icon: 'SettingsOutline',
    order: 200,
    permission: 'ROLE_USER',
  },
  {
    title: '用户管理',
    pid: 200,
    path: '/system/member',
    file: '/view/system/member/index.vue',
    icon: 'TeamOutlined',
    order: 201,
    permission: 'ROLE_USER',
  },
  {
    title: '菜单管理',
    pid: 200,
    path: '/system/menu',
    file: '/view/system/menu/index.vue',
    icon: 'MenuOutlined',
    order: 204,
    permission: 'ROLE_USER',
  },
];
