export default {
    getAllUser: "/user/getAllUser",
    deleteUser: "/user/deleteUser",
    editUser: "/user/editUser",
    uploadFile: "/common/uploadFile",
    createUser: "/user/createUser",
    operationList: "/user/operationList",
    role: "/role",
    branch: "/branch",
    menus: "/menu/getList",
    dictionaryAll: "/dictionary/findAll",
    createDic: "/dictionary/createDic",
    dictionaryFiled: "/dictionary/field",
    findDicByParentName: "/dictionary/findDicByParentName/",
    findDicById: "/dictionary/find",
    deleteDicById: "/dictionary/delete",
    createMenu: "/menu/createMenu",
    menuFiled: "/menu/field",
    menuDelete: "/menu/delete",
    gsc: {
        token: "/gsc/token",
        sentence: "/gsc/sentence",
    },
}
